config/routes.rb
Formation::Application.routes.draw do
  get "formations/home"
  resources :pages
  resources :users
  resources :formations

  post 'pages/:id', to: 'pages#submit'
  get 'pages/:id/thanks', to: 'pages#thanks'

  root :to => "formations#home"

end

app/models/formations.rb
class Formations < ActiveRecord::Base

	def create_user
		user = User.new
		user.first_name = self.first_name
		user.last_name = self.last_name
		user.email = self.email
		user.bank_account = self.bank_account
		user.routing_number = self.routing_number
		user.country = self.country
		user.save
		user
	end

	def create_page
		page = Page.new
		page.src = Page.iframe_to_src(self.src)
		page.amount = self.amount
		page.save
		page
	end


end

app/controllers/formations_controller.rb
class FormationsController < ApplicationController
  before_action :set_formation, only: [:show, :edit, :update, :destroy]

  # GET /formations
  # GET /formations.json


  def home
    @formations = Formations.new
  end


# Scaffold Action


  def index
    @formations = Formations.all
  end

  # GET /formations/1
  # GET /formations/1.json
  def show
  end

  # GET /formations/new
  def new
    @formation = Formations.new
  end

  # GET /formations/1/edit
  def edit
  end

  # POST /formations
  # POST /formations.json
  def create
    # binding.pry

    @formation = Formations.new(formation_params)
    # binding.pry

    respond_to do |format|
      if @formation.save
        @page = @formation.create_page
        @user = @formation.create_user
        format.html { redirect_to @page, notice: 'Formation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @formation }
      else
        format.html { render action: 'new' }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formations/1
  # PATCH/PUT /formations/1.json
  def update
    respond_to do |format|
      if @formation.update(formation_params)
        format.html { redirect_to @formation, notice: 'Formation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formations/1
  # DELETE /formations/1.json
  def destroy
    @formation.destroy
    respond_to do |format|
      format.html { redirect_to formations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formation
      @formation = Formations.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formation_params
      params[:formations].permit(:src, :name, :first_name, :country, :last_name, :email, :amount, :bank_account, :routing_number)
    end

end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/views/formations/_form.html.erb
<%= form_for(@formation) do |f| %>
  <% if @formation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@formation.errors.count, "error") %> prohibited this formation from being saved:</h2>

      <ul>
      <% @formation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/formations/edit.html.erb
<h1>Editing formation</h1>

<%= render 'form' %>

<%= link_to 'Show', @formation %> |
<%= link_to 'Back', formations_path %>

app/views/formations/home.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>Formation</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Styles
	================================================== -->
	<link href="/assets/bootstrap.css" rel="stylesheet">
	<link href="/assets/bootstrap-responsive.css" rel="stylesheet">
	<link href="/assets/font-awesome.css" rel="stylesheet">
	<link href="/assets/app.css" rel="stylesheet">

	<!-- Google Fonts
	================================================== -->
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans:300,400,400italic,700" >
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Ubuntu:300,400,400italic,700" >

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	</head>
	<body>
		<!-- Page Wrapper
		================================================== -->
		<div id="wrap" class="page">

		<!-- Navbar
		================================================== -->
		<div class="nav-wrap" style="position: fixed;width: 100%;">
			<div class="container">
				<div class="navbar">
					<div class="navbar-inner">
						<div class="container">
							<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</a>
							<a class="brand" href="index.html">
								<strong>Formation</strong>
							</a>
							<div class="nav-collapse collapse">
								<ul class="nav pull-right">
									<li class="active"><a href="#" class="active">iFrame</a></li>
									<li class="divider-vertical"></li>
									<li><a href="#">Personal Info</a></li>
									<li class="divider-vertical"></li>
									<li><a href="#">Charge Amount</a></li>
									<li class="divider-vertical"></li>
									<li><a href="#">Banking Information</a></li>
									<li class="divider-vertical"></li>
									<li><a href="#">Contact Us</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

<!-- Next DIV -->
<!-- Start Simple Form -->

		<%= simple_form_for @formations, :url => formations_path, :html => {:class => 'form-horizontal', :id => "bigdaddyform" } do |o| %>
		<!-- Page Header
		================================================== -->
		<div id="page-heading">
			<div class="page-header">
				<div class="container">
					<div class="row home">
						<div class="span12">
							<h1>Step One</h1>
						</div>
						<div class="span12" style="text-align: center;">
							<h4>Submit the Google iFrame that you want your contributors to fill out when they visit our page to pay you.</h4>
								<%= o.input :src, as: :text, :label => "Link to your iFrame", :input_html => {:autocomplete => "off", :wrap => 'hard', :style => "height:200px;width:400px;", :placeholder => "Paste your Google iFrame here: <iframe src=... ></iframe>"} %>
						</div>
					</div>
				</div>
			</div>

			<div class="home-cta">
				<div class="container">
					<div class="arrow-down"></div>
					<div class="home-cta-inner text-center">
						<h3>Now fill us in on a few things so that we can keep in contact with you and charge your customers the correct amount.
					<!-- 	<a href="#" class="btn cta-btn"><i class="icon-plus "></i>Find Out More</a></h3> -->
					</div>
				</div>
			</div>
		</div>

		<hr class="hr-spacer space35">

<!-- DIV TWO -->


		<!-- Home Container
		================================================== -->
		<div id="home">
			<div class="container">
				<div class="container">
					<div class="row home">
						<div class="span12">
							<h1>Step Two</h1>
						</div>
						<div class="span12" style="text-align: center;">
			 				<%= o.input :first_name, :label => "Your name", :input_html => {:placeholder => "Put your first name"} %>
			 				<%= o.input :last_name, :label => "Your name", :input_html => {:placeholder => "Put your last name"} %>
							<%= o.input :email, :label => "Your email", :input_html => {:placeholder => "Put your email"} %>
							<br>
							<br>
						</div>
					</div>
				</div><!-- End home ID -->
			</div>
		</div>


<!-- Next THREE -->



		<div id="page-heading">
			<div class="page-header">
				<div class="container">
					<br>
					<div class="row home">
						<div class="span12">
							<h1>Step Three</h1>
						</div>
						<div class="span12" style="text-align: center;">
							<h4>How much would you like to charge your customers?</h4>
 								<%= o.input :amount, :label => "Charge this amount." %>
								<br>
						</div>
					</div>
				</div>
			</div>
		</div>


<!-- Next DIV FOUR -->


		<div id="home">
			<div class="container">
				<div class="container">
					<div class="row home">
						<br>
						<div class="span12 row home">
							<h1>Last Step</h1>
						</div>
						<div class="span12" style="text-align: center;">				
							<%= o.input :bank_account, :label => "Bank Account #", :input_html => {:placeholder => "Put your name"} %>
							<%= o.input :routing_number, :label => "Bank Routing #", :input_html => {:placeholder => "Put your email"} %>
							<%= o.button :submit, :label => "Create Event", :input_html => { :id => "stripe"} %>
						</div>
						<br>
						<br>
					</div>
				</div><!-- End container -->	
			</div><!-- End container -->
		</div><!-- End home ID -->





		<div id="sub-footer-push"></div>
		<!-- Push Sub-Footer -->
		</div>


		<% end %>
<!-- End Simple Form -->
		<!-- End Form Wrapper -->

		<!-- End Page Wrapper -->

		<!-- Footer ================================================== -->
		<div id="footer">
			<div class="container">
				<div class="row">
					<div class="span4" style="text-align: center;">
						<h4>Formation Mission Statement</h4>
						<p>Formation is here to help organizers collect information from their attendees. All they need is an iFrame form from Google and an account for us to transfer money to.</p>
					</div>
					<div class="span4 testimonial" style="text-align: center;">
						<h4>Testimonials</h4>
						<blockquote>
						<p>"Formation is as light-weight as it gets, it helped me get relevent information from attendees and put together the event quickly."</p>
						<small>Jorge Olivero</small>
						</blockquote>
					</div>
					<div class="span3 contact pull-right" style="text-align: center;">
						<h4>Contact Us</h4>
						<ul class="unstyled contact-list" style="list-style: none;">
							<li><i class="icon-home contact-icon"></i>5B Streat, City 50987</li>
							<li><i class="icon-envelope-alt contact-icon"></i><a href="#">info@example.com</a></li>
							<li><i class="icon-phone-sign contact-icon"></i>1.541.258.2881</li>
							<li><i class="icon-print contact-icon"></i>1.541.854.8412</li>
							<li><i class="icon-globe contact-icon"></i><a href="#">http://www.example.com</a></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="span12 social">
						<h4>We're Social</h4>
						<ul class="unstyled social-list">
							<li><a href="#"><i class="icon-facebook icon-2x"></i></a></li>
							<li><a href="#"><i class="icon-twitter icon-2x"></i></a></li>
							<li><a href="#"><i class="icon-linkedin icon-2x"></i></a></li>
							<li><a href="#"><i class="icon-pinterest icon-2x"></i></a></li>
							<li><a href="#"><i class="icon-google-plus icon-2x"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<!-- Sub-Footer -Sticky
		================================================== -->
		<div id="sub-footer">
			<div class="container">
				<div class="row credits">
					<div class="span6"><p>&copy; 2013 Simply Flat</p></div>
					<div class="span6"><p class="pull-right">Theme by <a href="http://northify.com">Northify</a></p></div>
				</div>
		  	</div>
		</div>

		<!-- Javascript
		================================================== -->
			<script src="http://code.jquery.com/jquery-latest.js"></script>
			<script src="/assets/bootstrap.js"></script>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

		<script type="text/javascript">
			Stripe.setPublishableKey('pk_test_2okzzyyNxcLgaLc31XowCIVG');
			function stripeResponseHandler(status, response) {
			    if (response.error) {
			        // show the errors on the form
			        $(".payment-errors").text(response.error.message);
			    } else {
			        var form$ = $("#bigdaddyform");
			        // token contains id, last4, and card type
			        var token = response['id'];
			        // insert the token into the form so it gets submitted to the
			        form$.append("<input type='hidden' name='stripeToken' value='" + token + "'/>");
			        // and submit
			        form$.get(0).submit();
			    }
			}

			$("form#bigdaddyform").submit(function(e){
					var token = Stripe.bankAccount.createToken({
				            country: "US",
				            routingNumber: "110000000",
				            accountNumber: "000123456789",
				        }, stripeResponseHandler);
				e.preventDefault();
				return false;
			});
		</script>
	</body>
</html>

app/views/formations/index.html.erb
<h1>Listing formations</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @formations.each do |formation| %>
      <tr>
        <td><%= link_to 'Show', formation %></td>
        <td><%= link_to 'Edit', edit_formation_path(formation) %></td>
        <td><%= link_to 'Destroy', formation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Formation', new_formation_path %>

app/views/formations/new.html.erb
<h1>New formation</h1>

<%= render 'form' %>

<%= link_to 'Back', formations_path %>

app/views/formations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_formation_path(@formation) %> |
<%= link_to 'Back', formations_path %>